export const GET_TRACK_BY_NAME_REQUEST = 'GET_TRACK_BY_NAME_REQUEST';
export const GET_TRACK_BY_NAME_SUCCESS = 'GET_TRACK_BY_NAME_SUCCESS';
export const GET_TRACK_BY_NAME_FAIL = 'GET_TRACK_BY_NAME_FAIL';
